function names=sst_columns
names=[{'grid_voltage_pu','id_A_peak','iq_A_peak'},...
 arrayfun(@(k)sprintf('MV%d_V',k),1:9,'UniformOutput',false),...
 {'LV_V','grid_power_W','DAB_total_W','delivered_W','unmet_W','trip','grid_saturated','DAB_saturated','stored_energy_J','energy_residual_J'},...
 arrayfun(@(k)sprintf('DAB%d_phase_ratio',k),1:9,'UniformOutput',false)];
end
